#ifndef __VIDEO_H__
#define __VIDEO_H__

#include "../types.h"

#define CONSOLE_BACKGROUND_BLACK 0x00
#define CONSOLE_BACKGROUND_BLUE 0x10
#define CONSOLE_BACKGROUND_GREEN 0x20
#define CONSOLE_BACKGROUND_CYAN 0x30
#define CONSOLE_BACKGROUND_RED 0x40
#define CONSOLE_BACKGROUND_MAGENTA 0x50
#define CONSOLE_BACKGROUND_BROWN 0x60
#define CONSOLE_BACKGROUND_WHITE 0x70
#define CONSOLE_BACKGROUND_BLINK 0x80
#define CONSOLE_FOREGROUND_DARKBLACK 0x00
#define CONSOLE_FOREGROUND_DARKBLUE 0x01
#define CONSOLE_FOREGROUND_DARKGREEN 0x02
#define CONSOLE_FOREGROUND_DARKCYAN 0x03
#define CONSOLE_FOREGROUND_DARKRED 0x04
#define CONSOLE_FOREGROUND_DARKMAGENTA 0x05
#define CONSOLE_FOREGROUND_DARKBROWN 0x06
#define CONSOLE_FOREGROUND_DARKWHITE 0x07
#define CONSOLE_FOREGROUND_BRIGHTBLACK 0x08
#define CONSOLE_FOREGROUND_BRIGHTBLUE 0x09
#define CONSOLE_FOREGROUND_BRIGHTGREEN 0x0A
#define CONSOLE_FOREGROUND_BRIGHTCYAN 0x0B
#define CONSOLE_FOREGROUND_BRIGHTRED 0x0C
#define CONSOLE_FOREGROUND_BRIGHTMAGENTA 0x0D
#define CONSOLE_FOREGROUND_BRIGHTYELLOW 0x0E
#define CONSOLE_FOREGROUND_BRIGHTWHITE 0x0F

#define VGA_MEM ((volatile CHARACTER*)0xB8000)
#define VGA_COLS 80
#define VGA_ROWS 25
#define VGA_CELLS (VGA_COLS * VGA_ROWS)

#define CRTC_INDEX 0x3D4
#define CRTC_DATA 0x3D5
#define CRTC_CUR_LO 0x0F
#define CRTC_CUR_HI 0x0E
#define CRTC_START_LO 0x0D
#define CRTC_START_HI 0x0C

#define VGA_HW_BUFFER_CELLS 16384
#define CELL_MASK (VGA_HW_BUFFER_CELLS - 1)
#define WRAP(x) ((WORD)((x) & CELL_MASK))

#define DEFAULT_ATTR (CONSOLE_BACKGROUND_BLACK | CONSOLE_FOREGROUND_BRIGHTWHITE)

int kPrint(const char* str);
int kPrintColor(const char* str, BYTE attr);
void kPrintErr(const char* str);
void kPrintln(const char* str);
void kPrintlnColor(const char* str, BYTE attr);
void kClear(int clearStart);

#pragma pack(push, 1)

typedef struct kCharactorStruct {
    BYTE bCharactor;
    BYTE bAttribute;
} CHARACTER;

#pragma pack(pop)

#endif /*__VIDEO_H__*/